### ISSUE TITLE
ReturnJob exception on DisposeScope due to null trackingInfo

### ISSUE THREAD

**Issue by jafin** [alphacloud/Autofac.Extras.Quartz#17]
Haven't determined why I dont have trackingInfo but this code is crashing due to being returned a null trackingInfo.

```
public void ReturnJob(IJob job)
        {
            JobTrackingInfo trackingInfo;
            if (!RunningJobs.TryRemove(job, out trackingInfo))
            {
                s_log.WarnFormat("Tracking info for job 0x{0:x} not found", job.GetHashCode());
            }

          DisposeScope(job, trackingInfo.Scope);  //trackingInfo is null here.
        }
```

This occurs for jobs running in a windows service that is issued a stop command.

is it safe to change this to ?
```
public void ReturnJob(IJob job)
        {
            JobTrackingInfo trackingInfo;
            if (!RunningJobs.TryRemove(job, out trackingInfo))
            {
                s_log.WarnFormat("Tracking info for job 0x{0:x} not found", job.GetHashCode());
            } 
if (trackingInfo != null) {
          DisposeScope(job, trackingInfo.Scope);  //trackingInfo is null here.
        }
```

**Comment by shatl** [comment]
Interesting, I never saw this happening. Can you please check the logs for "Tracking info for job 0x not found" warning and check it it was already disposed. 

I'll update the code today.

**Comment by jafin** [comment]
Yes we're seeing the log event.   Just to mention, we're only seeing this on cancel/termination of the service (topshelf).  Normal operation trackingInfo is not null.

**Comment by shatl** [comment]
@jafin  Please update nuget package
