### ISSUE TITLE
One importand 

### ISSUE THREAD

**Issue by romka-04** [alphacloud/Autofac.Extras.Quartz#18]
Dear authors.

First of all I want to thank you for your work, time and efforts.
I have one suggeston. Could you please add to the README.md the following paragraph?

### Start the Quartz scheduler.

```
var scheduler = _container.Resolve<IScheduler>();
if ( !scheduler.IsStarted ) {
	scheduler.Start();
}
```

It will help a lot for users which rarely work with Quartz. For example I spent several hours before than I realized why quartz is not working.  

Thanks in advance!

**Comment by shatl** [comment]
thanks, will do
