### ISSUE TITLE
Jobs with dependencies..

### ISSUE THREAD

**Issue by billrawlinson** [alphacloud/Autofac.Extras.Quartz#20]
I am probably not seeing how to do this in a more straight forwrad manner; but I have some jobs with optional dependencies (set via properties).  

Using the QuartzAutofacJobsModule to register my jobs means the properties don't get wired.

To solve the problem for myself I just moved the "build" logic out of your module and reused it in my own module (while still using your factory module).

I ended up just needing to add `PropertiesAutowired()`

Is there a better way that I could have done this? Or is there a chance you could add that (even optionally) to the QuartzAutofacJobsModule?

Thanks

Here is my modules logic:

```cs
             builder.RegisterAssemblyTypes(_assemblyToScan)
               .Where(type => !type.IsAbstract && typeof(IJob).IsAssignableFrom(type))
               .PropertiesAutowired()
               .AsSelf().InstancePerLifetimeScope();
```

**Comment by shatl** [comment]
Hi @billrawlinson 

I assume that constructor injection/NullObject is not an option for you..

I'll make it an optional parameter in job registration module.

**Comment by billrawlinson** [comment]
I can use constructor injection. But then I need to basically repeat the same constructor arguments for all of my jobs (they all share a base Job class and use a custom "slack client" for reporting job success/failure back to the team.

The code is just a bit cleaner using property dependencies for this kind of stuff.

Alternatively, I could do something like autofac recommends for injecting log4net with the `AttachToComponentRegistration` method of a module. But that too seems like overkill for this particular need.

I appreciate the suggestion and your responsiveness to my question/request.  Thanks!

**Comment by shatl** [comment]
Makes sense. I'll publish new version soon.
