### ISSUE TITLE
How to use Autofac.Extras.Quartz with web appilcation MVC 4 & Autofac

### ISSUE THREAD

**Issue by sanjaypraja** [alphacloud/Autofac.Extras.Quartz#21]
I m trying to Quartz with my MVC 4 application & Autofac but scheduler is not running. I tried your given Sample project which is console based application. it is running fine but when i tried to use same thing in web application (MVC 4 & Autofac), it is not running. Please let me, how can I use in web application (MVC 4 & Autofac) if you have any sample please give us?

**Comment by sanjaypraja** [comment]
I discovered this by creating a new Test service that did nothing only use calling a function, and that worked being injected into a quartz job.
I am using Entity framework with Repository pattern to getting the data and try to fetch the data from services using Jobs then it's not working. Please help me.

**Comment by shatl** [comment]
You should not use web app to host the scheduler.
