### ISSUE TITLE
MissingMethodException with Autofac 4.0.0-rc3-280

### ISSUE THREAD

**Issue by jmvermeulen** [alphacloud/Autofac.Extras.Quartz#22]
With the latest Autofac 4.0.0-rc3-280 there is a runtime issue at my
`var container = builder.Build();`

Error:
An unhandled exception of type 'System.MissingMethodException' occurred in Autofac.dll
Additional information: Method not found: 'Autofac.Builder.IRegistrationBuilder`3<!0,!1,!2> Autofac.Builder.IRegistrationBuilder`3.PropertiesAutowired(Autofac.PropertyWiringOptions)'.

The problem seems to be in QuartzAutofacJobsModule:
`registrationBuilder.PropertiesAutowired(PropertyWiringOptions);`

There is no overload anymore with the parameter.

Possible solution:
`registrationBuilder.PropertiesAutowired(new DefaultPropertySelector(PropertyWiringOptions == PropertyWiringOptions.PreserveSetValues));`

**Comment by jmvermeulen** [comment]
This is my first public pull request, hope everything is alright :)
Please let me known if there is anything I can correct.

**Comment by shatl** [comment]
Thanks for the fix, @jmvermeulen !

Do you need a nuget package immediately or you can wait for AutoFac 4.0 release ?

**Comment by jmvermeulen** [comment]
Hi @shatl,

I've created a new PR #24 that targets develop, tried to fix the build issue regarding NUnit.

The dependencies are specified as Autofac (>= 3.5.2 && < 4.0.0), but still I was able to upgrade to the latest Autofac RC. I can imaging I'm not the only one who tries this scenario.

Maybe you can publish a new nuget and specify it as _prerelease_?

**Comment by shatl** [comment]
Thanks, will do soon

**Comment by shatl** [comment]
@jmvermeulen Done, please get 3.0.0-beta1

**Comment by jmvermeulen** [comment]
Thanks for your quick responses @shatl 
The new NuGet is working fine :+1:

**Comment by shatl** [comment]
@jmvermeulen last CI build of Autofac  has this method again.
