### ISSUE TITLE
Resolving from the correct lifetime scope

### ISSUE THREAD

**Issue by MichaelWeatherton** [alphacloud/Autofac.Extras.Quartz#25]
In the QuartzAutofacFactoryModule, I believe the delegate method for resolving the JobFactory could be improved to support tagged lifetime scopes.  Such as the popular Multitenant autofac contrib.  

This code appears to always resolve the root lifetime scope, which would not be correct in custom nested lifetime scopes:

```
builder.Register(c => new AutofacJobFactory(c.Resolve<ILifetimeScope>(), _lifetimeScopeName))
                .AsSelf()
                .As<IJobFactory>()
                .SingleInstance();

```

This may not be a defect since the module is there for convenience custom lifetime scope users can of course provide their own registrations. 

But I believe the correct lifetime can be achieved by using code along the lines of:

```
builder.Register(c =>
            {
                var ctx = c.Resolve<IComponentContext>();
                var lifetimeScope = ctx.Resolve<ILifetimeScope>();
                return new AutofacJobFactory(lifetimeScope, lifetimeScope.Tag.ToString());
            })
             .AsSelf()
             .As<IJobFactory>()
             .InstancePerTenant();
```

As an aside, I believe resolving from the component context in delegate resolve methods is "preferred" method so it always captures the correct scope.  In case this helps someone else, here is my full "override" of the QuartzAutofacFactoryModule that works with Autofac.Extras.Multitenant

```
var configuration = new NameValueCollection
            {
                [StdSchedulerFactory.PropertySchedulerInstanceName] =
                    string.Format("TaskScheduler {0}", Tenant.Current.TenantId)
            };
            builder.Register(c =>
            {
                var ctx = c.Resolve<IComponentContext>();
                var lifetimeScope = ctx.Resolve<ILifetimeScope>();
                return new AutofacJobFactory(lifetimeScope, lifetimeScope.Tag.ToString());
            })
             .AsSelf()
             .As<IJobFactory>()
             .InstancePerTenant();

            Func<IComponentContext,NameValueCollection> cfgProvider = ctx => configuration;

            builder.Register<ISchedulerFactory>(c =>
            {
                var ctx = c.Resolve<IComponentContext>();
                var autofacSchedulerFactory = new AutofacSchedulerFactory(cfgProvider(ctx), ctx.Resolve<AutofacJobFactory>());                   
                return autofacSchedulerFactory;
            })
            .InstancePerTenant();

            builder.Register(c => c.Resolve<ISchedulerFactory>().GetScheduler())
                .As<IScheduler>().InstancePerTenant();
```

Thanks!
Mike

**Comment by shatl** [comment]
Thanks for suggestion Mike.
My idea was to provide basic registration facilities which will allow other developers to customize them to fit their needs :)

I'll look at the Autofac.Multitenant implementation. Most probably this enhancement will go to separate package as it introduces extra dependency.

**Comment by MichaelWeatherton** [comment]
Sorry for the distraction of including the .InstancePerTenant(); in the code, which yes, would introduce another package dependency.  The main point was to first resolve the current IComponentContext from the initial IComponentContext: 

`  var ctx = c.Resolve<IComponentContext>();`

And then use ctx to resolve any further dependencies.  

In autofac, the initial IComponentContext supplied in the lambda expression registrations will always be the root scope.  This likely works for 99% of autofac implementations.  But even using vanilla autofac with no extra dependencies, this registration would not be compatible with any nested lifetime scope, such as tagged lifetime scope InstancePerMatchingLifetimeScope (what multitenant uses under the covers) or InstancePerRequest.  InstacePerRequest should not apply here since it wouldn't be a good idea to use jobs in the scope of an HttpRequest, but just illustrating the point.  This is sort of less than documented issue with autofac.  

Thanks for looking at this, and I really appreciate the package!

**Comment by shatl** [comment]
@MichaelWeatherton Can you create a sample to play with please? I never used Autofac.Multitenant so your sample will be very useful.

If I understand correctly, if scheduler is declared with InstancePerMatchingLifetimeScope() (which is Multitenant does), *c* will point to root context, rather than matching scope. Is this correct.

Thanks

**Comment by shatl** [comment]
@MichaelWeatherton any updates?
