### ISSUE TITLE
I don't want to register all IJob's

### ISSUE THREAD

**Issue by efaruk** [alphacloud/Autofac.Extras.Quartz#28]
Hi, what if I don't want to register all IJob implementations or if I have custom and multiple interface's instead of IJob. What if then?

Your QuartzAutofacJobsModule implementation only scan for IJob in the given assemblies; I think it is a blocking feature...

Regards...

**Comment by shatl** [comment]
Hi,
>Your QuartzAutofacJobsModule implementation only scan for IJob in the given assemblies; I think it is a blocking feature...
Can you elaborate what is blocking?

You can always create your custom module to filter and register jobs which will suit your needs. Pull requests are always welcome :)
