### ISSUE TITLE
Upgrade Autofac to v8.0.0

### ISSUE THREAD

**Issue by szyb** [alphacloud/Autofac.Extras.Quartz#280]
#### Is your feature request related to a problem? Please describe.
Yesterday Autofac 8.0 was released (https://github.com/autofac/Autofac/releases/tag/v8.0.0).

#### Describe the solution you'd like
Please update Autofac dependency

#### Describe alternatives you've considered
n/a

#### Additional context
n/a

**Comment by pantonis** [comment]
Any update on that?
