### ISSUE TITLE
Quartz 3 / NetStandard support

### ISSUE THREAD

**Issue by shatl** [alphacloud/Autofac.Extras.Quartz#33]
Upgrade to Quartz.Net 3;
Add .NET Standard support

**Comment by pianzide1117** [comment]
readly needed!

**Comment by shatl** [comment]
Replace IInterrubtableJob with check for JobExecutionContext.CancellationToken

**Comment by shatl** [comment]
@Newbe36524 will be ready soon

**Comment by Newbe36524** [comment]
@shatl Great

**Comment by shatl** [comment]
@MonkSoul Try latest unstable package
