### ISSUE TITLE
.net 4.5 support

### ISSUE THREAD

**Issue by ilyabreev** [alphacloud/Autofac.Extras.Quartz#36]
Do you plan to integrate 4.5 support?

**Comment by shatl** [comment]
Hi,

No plans for this. 

.NET 4.5 official support ended on Jan 12 2016 - https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/.
I'd recommend you to upgrade to newer version.

**Comment by ilyabreev** [comment]
Thanks. I think I'll upgrade.
