### ISSUE TITLE
Update TopShelf example to Quartz v3

### ISSUE THREAD

**Issue by shatl** [alphacloud/Autofac.Extras.Quartz#46]

**Comment by EtharAlali** [comment]
Dear gawd make this work! :) Dependency on Common.Logging.Log4Net1213 also seems hugely problematic for 4.6.2 (our project). For now, I'm going to have to rip out one of the two libraries to get a new solution working. The sample doesn't build (missing NuGet references) and is missing a NuGet package entry in any event.
