### ISSUE TITLE
Should call shutdown on IScheduler

### ISSUE THREAD

**Issue by wasabii** [alphacloud/Autofac.Extras.Quartz#48]
Right now, in order to have the process terminate properly, I have to create a custom Autofac component that resolves the `IScheduler` and invokes `Shutdown(false)` on it.

The `QuartzAutofacFactoryModule` should be registering this when the component is deactivated. It really should probably call `Start` too. It's a singleton, afterall. The module seems to claim ownership.

**Comment by shatl** [comment]
I want to keep module responsible for registration only.

Starting / stopping scheduler including error handling should be done externally.
