### ISSUE TITLE
does not support quartz.net new version(v3.0.0)

### ISSUE THREAD

**Issue by MonkSoul** [alphacloud/Autofac.Extras.Quartz#50]
This package does not support [quartz.net v3.0.0](https://www.quartz-scheduler.net/2017/12/30/quartznet-3.0-released.html). I hope to support the new version as soon as possible.

**Comment by shatl** [comment]
should be available soon

**Comment by shatl** [comment]
@MonkSoul  please refer to #33 to track Quartz.net v3 support
