### ISSUE TITLE
IScheduler registration question

### ISSUE THREAD

**Issue by aschaible** [alphacloud/Autofac.Extras.Quartz#57]
Hello,

I noticed on here, ConfigureAwait is set to false.

https://github.com/alphacloud/Autofac.Extras.Quartz/blob/master/src/Autofac.Extras.Quartz/QuartzAutofacFactoryModule.cs#L91

I'm not an async expert, but I've had issues where doing this where resources would not get disposed correctly.  Is there any reason for doing this?  I'm tracking down an issue where Quartz threads seem to be hanging open even though all work has finished, and I've spent hours in Quartz source code with no luck.

Any comments/guidance appreciated.

**Comment by shatl** [comment]
Hi Adam,
ConfigureAwait(false) instructs runtime not to capture synchronization context can continue execution (after awaiting) on current thread, it helps to prevent deadlocks. This is recommended practice for library code. 

This article will give you more details https://medium.com/bynder-tech/c-why-you-should-use-configureawait-false-in-your-library-code-d7837dce3d7f

**Comment by aschaible** [comment]
Thank you - I’ve read the article and understand what it does but I’ve found mixed results.

**Comment by shatl** [comment]
Can you elaborate on mixed results please?

**Comment by aschaible** [comment]
Yes, sorry for being vague.

We noticed that when ConfigureAwait(false) was used, the async thread was never garbage collected.  It probably doesn't matter in this case because the scheduler is just created once.

**Comment by shatl** [comment]
Task does not necessary represents a new thread, also threads are poolled.
