### ISSUE TITLE
You can not use KeyFilter WithAttributeFiltering

### ISSUE THREAD

**Issue by kadkin** [alphacloud/Autofac.Extras.Quartz#60]
You can not use KeyFilter

 var registrationBuilder = builder.RegisterAssemblyTypes(_assembliesToScan)
                .Where(type => !IsAbstract(type) && typeof(IJob).IsAssignableFrom(type) && FilterJob(type))
                .AsSelf()
                **.WithAttributeFiltering()**
                .InstancePerLifetimeScope();

**Comment by shatl** [comment]
Please elaborate
