### ISSUE TITLE
Sample code?

### ISSUE THREAD

**Issue by henrikweimenhog** [alphacloud/Autofac.Extras.Quartz#8]
Would be nice with some minimal instructions or sample code. 
Please add

**Comment by BotanMan** [comment]
@shatl 
Checked example, but really can't match it on my situation. I don't use Topshelf.
I have added

        container.RegisterModule(new QuartzAutofacFactoryModule());
        container.RegisterModule(new QuartzAutofacJobsModule(typeof(PollingWatcher).Assembly));

creating trigger and register the job

            IScheduler scheduler = StdSchedulerFactory.GetDefaultScheduler();
            scheduler.Start();

            IJobDetail job = JobBuilder.Create<PollingWatcher>().Build();

            Logger.AddMessage("Creating trigger");
            
            ITrigger trigger =
                TriggerBuilder.Create()
                    .WithSimpleSchedule(s => s.WithIntervalInSeconds(60))
                    .StartNow()
                    .Build();

            scheduler.ScheduleJob(job, trigger);

With parametless constructor it works but when I add some params that are registered with the same container - nothing happens.
As I see I need to register job in some other way... but I don't understand how. 
could you add some example for very simple case?

**Comment by shatl** [comment]
Hi,
Jobs are registered with QuartzAutofacJobsModule.
You are using default job factory which does not know about Autofac.
I'll add example this week.

Regards, Vitaliy

**Comment by shatl** [comment]
@BotanMan Just resolve ISchedulerFactory from containser, use it to create and start Sheduler

**Comment by BotanMan** [comment]
@shatl Thank you, seems I managed to do this:

            IScheduler sched = container.Resolve<IScheduler>();
            sched.JobFactory = new AutofacJobFactory(container.Resolve<ILifetimeScope>(), "job-scope");
            sched.Start();


            IJobDetail job = JobBuilder.Create<PollJob>()
               .WithIdentity("PollJob")
               .Build();

            ITrigger trigger = TriggerBuilder.Create()
                .WithIdentity("PollJobTrigger")
                .WithSimpleSchedule(x => x
                    .RepeatForever()
                    .WithIntervalInSeconds(5)
                )
                .StartNow()
                .Build();
